gpt-config {
  vocab_size = 199998
  context_length = 256 // adjust as needed
  emd_dim = 60
  n_heads = 12
  n_layers = 12
  drop_rate = 0.01
  qkv_bias = false
}
training-config {
  file = "/Users/dooby1/Downloads/wikiarchive/AllCombined.txt"
  ratio = 0.9
  limit = 140
  batch_size = 20
}